#!/bin/bash

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


if [ -z "$1" ]; then
  "${SCRIPT_PATH}/ansible-docker-run" ansible-vault decrypt "$@"
else
  echo "Decrypt from stdin is not yet supported. Use 'ansible-bash' and run you command there"
  exit 1
fi

