#!/bin/bash
# Run the Ansible docker image
# This script is called from the other one

# Set the azure configuration
# You need to copy the file azure-conf-dist.cmd to azure-conf.cmd and set your values
AZURE_CONF_FILE="azure-conf.cmd"

if [ -f "$AZURE_CONF_FILE" ]; then
   # shellcheck disable=SC1090
   source "$AZURE_CONF_FILE"
fi

# Default Ansible version if not set
ANSIBLE_VERSION=${ANSIBLE_VERSION:-2.9}

declare -a args=("run" "--rm")

if [ "$1" == "bash" ]; then
  # The input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'
    # Docker should not run as an interactive session (only for the docker-bash script)
  args+=("--entrypoint" "/ansible/bin/entrypoint.sh" "-it")
fi

# Fixed working directory in the Dockerfile
DOCKER_WORKING_DIR="/ansible/playbooks"

# Default values if not defined
ANSIBLE_CONFIG=${ANSIBLE_CONFIG:-ansible.cfg}
ANSIBLE_HOME=${ANSIBLE_HOME:-$DOCKER_WORKING_DIR}

echo "Env (Script)"
echo "DOCKER_ANSIBLE_VERSION : $ANSIBLE_VERSION"
echo
echo "Env (Inside Docker)"
echo "ANSIBLE_CONFIG : $DOCKER_WORKING_DIR/$ANSIBLE_CONFIG"
echo "ANSIBLE_HOME   : $DOCKER_WORKING_DIR/$ANSIBLE_HOME"
echo

# Cygwin to Docker Pwd format
# --volume /c/code/infra:/ansible/playbooks
PWD_DOCKER_FORMAT=$(cygpath -aw . | tr 'C:' '/c' | tr '\\' '/')

# Azure
if [ -n "$AZURE_CLIENT_ID" ]; then
    args+=("--env" "AZURE_CLIENT_ID=\"$AZURE_CLIENT_ID\"")
fi
if [ -n "$AZURE_SECRET" ]; then
    args+=("--env" "AZURE_SECRET=\"$AZURE_SECRET\"")
fi
if [ -n "$AZURE_SUBSCRIPTION_ID" ]; then
    args+=("--env" "AZURE_SUBSCRIPTION_ID=\"$AZURE_SUBSCRIPTION_ID\"")
fi
if [ -n "$AZURE_TENANT" ]; then
    args+=("--env" "AZURE_TENANT=\"$AZURE_TENANT\"")
fi

# Run Docker command
docker "${args[@]}" \
	--volume "$PWD_DOCKER_FORMAT:$DOCKER_WORKING_DIR" \
	--env ANSIBLE_CONFIG="$DOCKER_WORKING_DIR/$ANSIBLE_CONFIG" \
	--user ansible \
  --env ANSIBLE_HOME="$DOCKER_WORKING_DIR/$ANSIBLE_HOME" \
	gerardnico/ansible:"$ANSIBLE_VERSION" \
	"$@"

