#!/bin/bash
# Run the Ansible docker image
# This script is called from the other one

# Set the azure configuration
# You need to copy the file azure-conf-dist.cmd to azure-conf.cmd and set your values
AZURE_CONF_FILE="azure-conf.cmd"

if [ -f "$AZURE_CONF_FILE" ]; then
   # shellcheck disable=SC1090
   source "$AZURE_CONF_FILE"
fi

# Default Ansible version if not set
ANSIBLE_VERSION=${ANSIBLE_VERSION:-2.9}

if [ "$1" == "bash" ]; then
  ENTRY_POINT="--entrypoint /ansible/bin/entrypoint.sh"
  # The input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'
  # Docker should not run as an interactive session (only for the docker-bash script)
  INTERACTIVE="-it"
else
  ENTRY_POINT=""
  INTERACTIVE=""
fi

# Fixed working directory in the Dockerfile
DOCKER_WORKING_DIR="/ansible/playbooks"

# Default values if not defined
ANSIBLE_CONFIG=${ANSIBLE_CONFIG:-ansible.cfg}
ANSIBLE_HOME=${ANSIBLE_HOME:-$DOCKER_WORKING_DIR}

echo "Env (Script)"
echo "DOCKER_ANSIBLE_VERSION : $ANSIBLE_VERSION"
echo
echo "Env (Inside Docker)"
echo "ANSIBLE_CONFIG : $DOCKER_WORKING_DIR/$ANSIBLE_CONFIG"
echo "ANSIBLE_HOME   : $DOCKER_WORKING_DIR/$ANSIBLE_HOME"
echo

# --volume c/code/infra\:/ansible/playbooks
PWD=$(cygpath -aw . | tr \\\\ /)

# Run Docker command
docker run \
	--rm \
	--volume "$PWD:$DOCKER_WORKING_DIR" \
	--env ANSIBLE_CONFIG="$DOCKER_WORKING_DIR/$ANSIBLE_CONFIG" \
	"$INTERACTIVE" \
	gerardnico/ansible:"$ANSIBLE_VERSION" \
	"$@"

#	--user ansible \
#	--env ANSIBLE_HOME="$DOCKER_WORKING_DIR/$ANSIBLE_HOME" \

#	$ENTRY_POINT \
#	--env AZURE_CLIENT_ID="$AZURE_CLIENT_ID" \
#	--env AZURE_SECRET="$AZURE_SECRET" \
#	--env AZURE_SUBSCRIPTION_ID="$AZURE_SUBSCRIPTION_ID" \
#	--env AZURE_TENANT="$AZURE_TENANT" \
