#!/bin/bash

# Test for docker hub with --no-cache
docker build --no-cache -t "gerardnico/ansible:2.7" 2.7
docker build -t "gerardnico/ansible:2.7" Dockerfiles/2.7

# 2.8
docker build -t "gerardnico/ansible:2.8" Dockerfiles/2.8

# 2.9
docker build -t "gerardnico/ansible:2.9" Dockerfiles/2.9
docker push "gerardnico/ansible:2.9"

